import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Montserrat,
  Plus_Jakarta_Sans,
  Geologica,
} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageLoader from "@/components/Loader";
import Socials from "@/components/Socials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geog = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "K&F Video Production",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${montserrat.variable} ${geog.variable} antialiased justify-center items-center`}
      >
        <PageLoader />
        <Socials />
        <Header />
        {children}
      </body>
    </html>
  );
}
